### ISSUE TITLE
Some colours are grey

### ISSUE THREAD

**Issue by richfitz** [gaborcsardi/crayon#17]
```r
message(crayon::make_style("hotpink")("asdfa"))
```

**Comment by richfitz** [comment]
Beautiful, thanks!

**Comment by richfitz** [comment]
This is a problem again, at least on my system (linux, terminal, R 3.2.2 with github and CRAN versions of crayon).  Can you reopen?  Any idea how to detect regressions?

**Comment by richfitz** [comment]
![crayon](https://cloud.githubusercontent.com/assets/1558093/11957103/33624f6a-a8b7-11e5-8260-17742fbaaa8f.png)

**Comment by gaborcsardi** [comment]
I am not sure if this is a regression. But it could be. What does `crayon::num_colors()` say? `Sys.getenv()`? (Remove authentication tokens!)

**Comment by richfitz** [comment]
You're right, sorry for the false alarm -- my OSX system displays the colour correctly (reporting 256 for `num_colors()`) while Linux is reporting 8 colours.

That's coming from `system("tput colors")` reporting 8 colours, even though this is definitely not an 8 colour terminal.

Forcing the terminal type by running   

```
TERM=xterm-256color tput colors
```

gives the right number.  Likewise,

```
TERM=xterm-256color Rscript -e 'message(crayon::make_style("hotpink")("asdfa"))'
```

prints the pink correctly.  So while this is definitely a configuration issue, [this](https://push.cx/2008/256-color-xterms-in-ubuntu) suggests that this 8 colour reporting/256 colour capability configuration is typical.  [This SO answer](http://unix.stackexchange.com/a/23789) might provide a less stringent test, as it seems likely that 256 colour support will be more common than 8 colour support this century :smile:

**Comment by gaborcsardi** [comment]
Thanks for the links. The thing is, the method suggested in the SO answer does not work for me on OSX, in iterm. :/ I think if you know that your terminal supports 256 colors, you can just set `TERM` accordingly. This is the simplest solution, and I suspect that it is the only safe one that works on all platforms.

**Comment by richfitz** [comment]
What would happen if rather than getting the result of tput just assuming 256?  Is there even an 8 colour terminal easily available to see how it looks?  Being able to rely in >8 colours makes using the package a lot easier (otherwise all end users will have to set TERM, even if it's several dependencies deep).  I can dig around and see what the node packages for this do if that's useful.  Or you can keep the current behaviour, which I agree is probably safest.

**Comment by gaborcsardi** [comment]
> What would happen if rather than getting the result of tput just assuming 256? 

I have no idea.

> Is there even an 8 colour terminal easily available to see how it looks? 

Emacs is surely 8 color. 

> Being able to rely in >8 colours makes using the package a lot easier (otherwise all end users will have to set TERM, even if it's several dependencies deep).

I can default to 256 if `TERM` is `xterm`. I guess this solves most issues. But then I need a mechanism to fall back to 8 colors.

> I can dig around and see what the node packages for this do if that's useful. 

This is what the most popular node package does: https://github.com/chalk/supports-color/blob/master/index.js 

So how about defaulting to 256 if `TERM` is `xterm`?

**Comment by richfitz** [comment]
In emacs, when forcing 256 colours with:

```r
crayon::make_style("hotpink", colors=256)
```

I get unstyled output, which doesn't seem too tragic a failing.

Looks like node is going with 8 colours with xterm.  And apparently setting TERM is liable to cause unspecified things.  What a mess.

**Comment by gaborcsardi** [comment]
Please reopen if you have issues.
