### ISSUE TITLE
crayon errors on winbuilder

### ISSUE THREAD

**Issue by jimhester** [gaborcsardi/crayon#18]
When I submitted jimhester/covr@4024dc42f46869f8a0b2925a21cd188bfa43a50e to [win-builder](http://win-builder.r-project.org) it resulted in the following test errors (https://gist.github.com/jimhester/d59cda542277626e50e9).

Error 1 is un-releated to crayon, however errors 2 and 3 seem to be failure to load the crayon namespace on the build machine.

The relevant error messages are [unknown terminal "cygwin"](https://gist.github.com/jimhester/d59cda542277626e50e9#file-testthat-rout-fail-L53-L55) and [traceback](https://gist.github.com/jimhester/d59cda542277626e50e9#file-testthat-rout-fail-L120-L144)

Looking at the traceback I am guessing the issue is at [R/has_color.r#L79-L81](https://github.com/gaborcsardi/crayon/blob/e41a03acd36ad8e0e34e6cfbfe4818a41f45983e/R/has_color.r#L79-L81), for some reason cols does not being set, but the system command is also not throwing an error.

Sorry I don't have a good reproduceable example, I don't want to spam win-builder to create one.  Any ideas on a fix?

**Comment by gaborcsardi** [comment]
Hmmm, this is a case when tput is available on the system, but it is not reporting anything useful for the current terminal. I hope it is retuning a non-zero status at least.

I am actually testing it on windows, but windows machines usually don't have tput AFAIK, so they are fine.

Anyway, this is something I need to fix.
