### ISSUE TITLE
Align `col_strsplit` to `strsplit`, warts and all?

### ISSUE THREAD

**Issue by brodieG** [gaborcsardi/crayon#26]
Consider:

    > strsplit(" a b ", " ")
    [[1]]
    [1] ""  "a" "b"

    > col_strsplit(" a b ", " ")
    [[1]]
    [1] ""  "a" "b" ""

I'd argue that the `crayon` output is more correct.  It is, however, different from what `strsplit` does.  Would you consider accepting a PR that "fixes" this?  If no, not a big deal.  I'm going to have to work around this issue anyway since for the time being I'm relying on the CRAN version of this package.

**Comment by gaborcsardi** [comment]
Yes, what `strsplit` is doing is also "correct", so we can fix `col_strsplit`.

Looks like `col_strsplit` just adds an extra `""` if `split` appears at the end of the string.

**Comment by brodieG** [comment]
Loosely related, [is this](https://github.com/gaborcsardi/crayon/blob/master/R/utils.r#L93):

      if (!empty) res[ res$length != 0, , drop = FALSE ]
      res

Supposed to be:

      if (!empty) {
        res[ res$length != 0, , drop = FALSE ]
      } else res

It seems so, but if I fix that, then [`map_to_ansi`](https://github.com/gaborcsardi/crayon/blob/b2037bc3902708b87805b0c602e574ef6dd28bfe/R/string_operations.r#L7) will change as it will start dropping empty split hunks, which I guess it doesn't do now.  That's easy enough to change by specifying the `empty` parameter to `TRUE` to preserve current behavior, but I just wanted to check with you to make sure I'm not missing something.
