### ISSUE TITLE
Make start() a generic function, so it does not mask start() functions from stats and GenomicRanges

### ISSUE THREAD

**Issue by jmw86069** [gaborcsardi/crayon#32]
My test case, load the packages "GenomicRanges" and "crayon" in R.  Then try to run start() on a GRanges object, and it fails to find the appropriate start() function.  As I loosely understand generic functions, the presence of a non-generic function overrides or at least confounds the process of dispatching a generic function.

I note that start() also masks the generic function stats::start(), which is an easier reproducible case::
```
start(1:10);
library(crayon);
start(1:10);
stats::start(1:10);
```

Final note: I really appreciate this package!  I had been using the officially retired xterm256 package which I had kept a copy of for my own purposes -- I am much happier using a legit R package, and color has been extremely useful for my daily viewing of R console output. :-)

**Comment by gaborcsardi** [comment]
@jmw86069 Thanks for the feedback.

Yes, I suppose I can make it generic.

If you use `crayon` in a package, then I suggest to call crayon functions with `::` instead of importing the whole package, though.

**Comment by jmw86069** [comment]
Thanks so much for the rapid update!  I tested the newest code and it resolved my problem.  :-)

To be fair, I don't know if there is an elegant way to handle masked generic functions as a user, other that prepending the `packagename::`.  My issue was not while developing a package, but in just using R and GenomicRanges.  Once I used `library(crayon);` I could no longer use `start(GRanges)`, which meant a lot of my R code just stopped working.  I could go back and change all instances of `start()` to `GenomicRanges::start()`, but that seemed non-ideal, especially since some of those functions might be `IRanges::start()`.  The purpose of the generic functions is so I don't have to care which package does the details.  :-)

Ultimately my issue is likely with R itself.  Any package which chooses to override a generic function would break a bunch of existing R code, e.g. if you didn't rename dim() to blurred() I suspect it would cause quite some problems!  Seems like a fairly large risk, totally dependent upon package creators not to trample existing functions they may not be aware of.  But again, not your problem, and I much appreciate your very rapid update!

**Comment by gaborcsardi** [comment]
Sure, no worries. 

One way to go around these problems is to push as much code as possible to packages, and then import selectively. But I understand that building R packages is a pain, still.

**Comment by jmw86069** [comment]
Just a friendly ping, this error is still evident in the released version of crayon, version 1.3.1.  I used `devtools::install_github("gaborcsardi/crayon")` to fix it for me.  But for anyone not using the github version, or unable to install it in a production environment, a release of the latest crayon would be helpful.  I can file a new issue if that the appropriate way forward.

Note that the error comes from released Bioconductor packages, and not from my own R code.  There are more than a few widely-used Bioconductor packages calling start() as a generic function, apparently by necessity. For those packages, the start() function is applied to a variety of objects which implement range features, often handled by various different packages.  It would not be possible to prefix a package name in all cases, since they rely upon the generic start method to find the appropriate function -- unless some other mechanism for handling generic functions is available that I've not seen yet.

On another positive note -- yes, I really am this motivated to keep color in my terminal. 👍  :-)

**Comment by gaborcsardi** [comment]
Note that this is the bug in the BioC or whatever packages that use `start` without importing it. It is not a bug in crayon.

For fixing your own stuff, just don't import start, and use it with the `::` notation if you need it at all.

**Comment by jmw86069** [comment]
I understand your point, and concede it is not a bug in crayon... it is more of an issue in how R handles non-generic and generic functions, which crayon has not avoided.  ;-)  Sorry if that sounds critical, due respect to your work to release a useful package at no cost.  It isn't your responsibility to recognize every possible generic function and avoid it, but it also isn't feasible for me to impose a change on 20+ package authors, to prefix:: a function.  I thought avoiding the prefix:: was one main purpose of the method dispatch mechanism in R (where applicable.)  But this is not a question for you, so I digress.

Apparently you're partly correct in suggesting that BioC could try to avoid conflicts.  Armed with more keywords, I was able to find a Bioconductor discussion on S3 and S4 generics, and how they attempt to avoid conflicting generic functions:

https://stat.ethz.ch/pipermail/bioc-devel/2011-September/002757.html

Their solution was to create a package "BiocGenerics" which defines a long list of generic functions.  The only issue is that if crayon is loaded after BiocGenerics, it still breaks.  If BiocGenerics is loaded after crayon, the start() function works.

All that said, will crayon have a new version released?

**Comment by gaborcsardi** [comment]
Are you sure that just *loading* crayon is bad? Don't you have to *attach* it? `crayon::start` is not generic, I believe.

**Comment by gaborcsardi** [comment]
Just submitted a new version, hopefully it'll go through.

**Comment by gaborcsardi** [comment]
"on CRAN now"

Please reopen this if you still have problems. Thanks.
