### ISSUE TITLE
256 colour mapping

### ISSUE THREAD

**Issue by richfitz** [gaborcsardi/crayon#33]
Not sure how much you care, but I think that the current rgb -> ansi256 colour mapping is fairly inaccurate and could be fixed fairly easily.

Here's a case I have run into.  The colour "#ADB9CA" is a mid gray, very slightly blue.  

![target](https://cloud.githubusercontent.com/assets/1558093/14636943/59234bd8-0626-11e6-8982-b05498745138.png)

With crayon it renders the blue quite strongly:

![issue](https://cloud.githubusercontent.com/assets/1558093/14636956/63ee8b86-0626-11e6-9f2c-99af0bfb3bb3.png)

In [rainbowrite](https://github.com/richfitz/rainbowrite/blob/master/R/paint.R#L102-L121) I ported code from the rainbow paint gem.  It's not very long.

Would you like a PR that does the translations this way?

**Comment by richfitz** [comment]
FWIW, this is how the R graphics device renders that colour: ![plot](https://cloud.githubusercontent.com/assets/1558093/14637019/b3ec1676-0626-11e6-998e-851b8db87970.png)

**Comment by gaborcsardi** [comment]
Yes, a pr would be great! My implementation is quite naive.... Thanks much!
