### ISSUE TITLE
Ideas to make it easier to style text in conjunction with glue

### ISSUE THREAD

**Issue by jimhester** [gaborcsardi/crayon#44]
Ideally it would be nice if something like the following syntax would work.

```r
library(crayon)
glue::glue("{blue}foo{red}bar{reset}baz")
```

I think it may be possible by defining a `as.character.crayon` method that just outputs the escapes for the crayon object (if any).

**Comment by gaborcsardi** [comment]
> I think it may be possible by defining a as.character.crayon method that just outputs the escapes for the crayon object (if any).

You mean like this?
```r
library(crayon)
start(red)
#> [1] "\033[31m"
finish(red)
#> [1] "\033[39m"
```

**Comment by gaborcsardi** [comment]
Oh, I see what you mean

**Comment by jimhester** [comment]
yeah, maybe just 
```r
as.character.crayon <- function(x, ...) {
  start(x)
}
```
Would do it...

**Comment by gaborcsardi** [comment]
I think it is a bit awkward that you need to reset. No?

**Comment by jimhester** [comment]
A bit yeah, but I don't see an easy way to avoid it...

**Comment by gaborcsardi** [comment]
I think it is a good idea, but compared to 

```r
glue(blue("foo"), red("bar"), "baz")
```
the proposed
```r
glue::glue("{blue}foo{red}bar{reset}baz")
```
is not much better imo. But we probably just need better examples for motivation, I think. Examples that actually use substitution.

**Comment by jimhester** [comment]
I think the main benefit is you don't have to deal with quoting and unquoting in longer text.
```r
glue("{red}Warning:{reset} this is a warning message") 

# Or
glue("
{bold}A title of a very important piece{reset}

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. {blue}Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. {green}Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. {red} Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.{reset}
")
```

The resets are a bit of a pain, but not too bad...
